"use client";

import type { CSSProperties, ReactNode } from "react";
import { useMemo } from "react";
import type { KPIBenchmark } from "@/lib/kpiUtils";
import type { DownloadReportData } from "@/components/shared/DownloadReportButton";
import {
  evaluateDGDependency,
  evaluateEnergyIntensity,
  evaluateRecyclingRate,
  evaluateRenewableEnergy,
  evaluateTankerWaterDependency,
  evaluateWaterIntensity,
  evaluateWaterReuse,
  evaluateWasteSegregation,
} from "@/lib/kpiUtils";
import {
  A4_PORTRAIT_CSS_PX,
  PDF_CONTENT_INSET_PX,
} from "@/lib/pdf/pdfConstants";

const BRAND = {
  green: "#15803d",
  yellow: "#b45309",
  red: "#b91c1c",
  blue: "#1d4ed8",
  /** Section labels — darker for raster/PDF legibility */
  slate: "#334155",
  ink: "#0f172a",
  /** Body secondary — stronger than default muted for small type */
  muted: "#334155",
  line: "#e2e8f0",
  soft: "#f8fafc",
};

const stageColor = (score: number) => {
  if (score >= 90) return BRAND.green;
  if (score >= 75) return "#16a34a";
  if (score >= 60) return BRAND.yellow;
  if (score >= 40) return "#ea580c";
  return BRAND.red;
};

const riskColor: Record<string, string> = {
  Low: BRAND.green,
  Medium: BRAND.yellow,
  "Medium-High": "#ea580c",
  High: BRAND.red,
};

const roadmapColor: Record<string, string> = {
  Immediate: BRAND.red,
  "0–3 Months": "#ea580c",
  "3–6 Months": BRAND.yellow,
  "6–12 Months": BRAND.blue,
  "12+ Months": "#6d28d9",
};

const formatCertName = (name: string) => {
  const map: Record<string, string> = {
    ISO14001: "ISO 14001",
    ISO50001: "ISO 50001",
    NABH: "NABH",
    IGBC: "IGBC Healthcare",
    LEED: "LEED",
    WELL: "WELL",
    BRSR: "BRSR",
    GRI: "GRI",
    CDP: "CDP",
  };
  return map[name] || name;
};

const typeMeta: CSSProperties = {
  fontSize: 9,
  fontWeight: 700,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  color: BRAND.slate,
  margin: 0,
  lineHeight: 1.4,
};

/** Stable stack for html2canvas (avoid variable font metrics clipping in PDF raster). */
const printFont = "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";

const grid8 = 8;
/** Vertical rhythm between major blocks (tighter = less blank PDF space). */
const sectionGap = grid8 * 1.25;
/** Card interior padding */
const cardPad = grid8 * 1.5;

function Gauge({ value, size = 108 }: { value: number; size?: number }) {
  const radius = 36;
  const circumference = Math.PI * radius;
  const offset = circumference - (value / 100) * circumference;
  const color = stageColor(value);
  return (
    <svg width={size} height={size * 0.62} viewBox="0 0 120 80" aria-hidden="true">
      <path d="M16,64 A36,36 0 0,1 104,64" fill="none" stroke="#e2e8f0" strokeWidth="8" strokeLinecap="round" />
      <path
        d="M16,64 A36,36 0 0,1 104,64"
        fill="none"
        stroke={color}
        strokeWidth="8"
        strokeLinecap="round"
        strokeDasharray={circumference}
        strokeDashoffset={offset}
      />
      <text x="60" y="52" textAnchor="middle" fontSize="22" fontWeight="800" fill={BRAND.ink} fontFamily={printFont}>
        {value}
      </text>
      <text x="60" y="72" textAnchor="middle" fontSize="10" fill={BRAND.muted} fontFamily={printFont}>
        Overall
      </text>
    </svg>
  );
}

function ReportFooter({
  orgName,
  pageLabel,
  generatedLabel,
}: {
  orgName: string;
  pageLabel: string;
  generatedLabel: string;
}) {
  return (
    <div
      style={{
        position: "absolute",
        left: PDF_CONTENT_INSET_PX.left,
        right: PDF_CONTENT_INSET_PX.right,
        bottom: 18,
        paddingTop: 10,
        borderTop: `1px solid ${BRAND.line}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        flexWrap: "wrap",
        fontSize: 9,
        color: BRAND.slate,
        fontFamily: printFont,
        letterSpacing: "0.02em",
        lineHeight: 1.35,
      }}
    >
      <span style={{ fontWeight: 600 }}>{orgName} ESG Sustainability Review</span>
      <span style={{ color: "#cbd5e1" }}>•</span>
      <span>Generated by ESGroww</span>
      <span style={{ color: "#cbd5e1" }}>•</span>
      <span>{generatedLabel}</span>
      <span style={{ color: "#cbd5e1" }}>•</span>
      <span style={{ fontWeight: 600 }}>{pageLabel}</span>
    </div>
  );
}

function PrintPage({
  children,
  footer,
}: {
  children: ReactNode;
  footer?: ReactNode;
}) {
  const { width, height } = A4_PORTRAIT_CSS_PX;
  const inset = PDF_CONTENT_INSET_PX;
  /** Reserve space so body copy does not collide with the absolute footer band. */
  const footerReserve = 36;
  return (
    <div
      data-pdf-page=""
      style={{
        width,
        height,
        position: "relative",
        overflow: "hidden",
        /* Full-bleed white: template PDF must not show through margins (fixes “Summary Report” ghosting). */
        backgroundColor: "#ffffff",
        boxSizing: "border-box",
        paddingTop: inset.top,
        paddingRight: inset.right,
        paddingBottom: inset.bottom + footerReserve,
        paddingLeft: inset.left,
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "stretch",
          justifyContent: "flex-start",
          minHeight: 0,
        }}
      >
        {children}
      </div>
      {footer}
    </div>
  );
}

function PrintCard({ children, style }: { children: ReactNode; style?: CSSProperties }) {
  return (
    <div
      style={{
        background: "#ffffff",
        border: `1px solid ${BRAND.line}`,
        borderRadius: 4,
        padding: cardPad,
        boxSizing: "border-box",
        ...style,
      }}
    >
      {children}
    </div>
  );
}

function kpiImpactStyle(kpi: KPIBenchmark) {
  const insufficient = kpi.status === "Insufficient Data";
  if (insufficient) return { bg: "#f1f5f9", fg: BRAND.slate, label: "Data" };
  if (kpi.scoreImpact === "Full") return { bg: "#dcfce7", fg: BRAND.green, label: "Strong" };
  if (kpi.scoreImpact === "Partial") return { bg: "#fef9c3", fg: BRAND.yellow, label: "Watch" };
  return { bg: "#fee2e2", fg: BRAND.red, label: "Act" };
}

export function ReportPdfCapture({ data }: { data: DownloadReportData }) {
  const score = Math.round(data.overallScore);
  const orgName = data.orgName ?? "Organization";
  const categoryScores = data.categoryScores ?? { energy: 0, water: 0, waste: 0, governance: 0 };
  const certEntries = Array.isArray(data.certificationReadiness) ? data.certificationReadiness : [];
  const emissions = data.emissions ?? { scope1: 0, scope2: 0, scope3: 0 };
  const strengths = data.strengths ?? [];
  const gaps = data.gaps ?? [];
  const regulatory = data.regulatoryReadiness ?? [];
  const roadmapEntries = data.roadmap ?? [];

  const annEl = data.annualizedValues.electricity ?? 0;
  const annWa = data.annualizedValues.water ?? 0;
  const sqft = data.builtUpArea ?? data.orgBuiltUpArea ?? 0;
  const renPct = data.percentages?.renewableEnergy ?? 0;
  const wRePct = data.percentages?.waterRecycling ?? 0;
  const wsePct = data.percentages?.wasteRecycling ?? 0;

  const generatedLabel = new Date().toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const kpiRows = useMemo(() => {
    const intensityEl = annEl > 0 && sqft > 0 ? annEl / sqft : null;
    const intensityWa = annWa > 0 && sqft > 0 ? annWa / sqft : null;
    const items = [
      { title: "Energy intensity", unit: "kWh/sqft/yr", icon: "⚡", kpi: evaluateEnergyIntensity(intensityEl) },
      { title: "Water intensity", unit: "KL/sqft/yr", icon: "💧", kpi: evaluateWaterIntensity(intensityWa) },
      { title: "Renewable energy", unit: "%", icon: "☀️", kpi: evaluateRenewableEnergy(renPct) },
      { title: "Water reuse", unit: "%", icon: "🔄", kpi: evaluateWaterReuse(wRePct) },
      { title: "Recycling rate", unit: "%", icon: "♻️", kpi: evaluateRecyclingRate(wsePct) },
      { title: "Waste segregation", unit: "%", icon: "🗑️", kpi: evaluateWasteSegregation(wsePct) },
      { title: "Tanker dependency", unit: "%", icon: "🚛", kpi: evaluateTankerWaterDependency(0) },
      { title: "DG dependency", unit: "%", icon: "🛢️", kpi: evaluateDGDependency(0) },
    ];
    return items;
  }, [annEl, annWa, sqft, renPct, wRePct, wsePct]);

  const recommendations = useMemo(() => {
    const out: string[] = [];
    const topGap = gaps[0]?.text;
    if (topGap) out.push(`Close the highest-severity gap: ${topGap}`);
    const topRoad = roadmapEntries[0];
    if (topRoad) out.push(`Prioritize roadmap item (${topRoad.timeline}): ${topRoad.action}`);
    const lowReg = regulatory.slice().sort((a, b) => a.readiness - b.readiness)[0];
    if (lowReg) out.push(`Lift regulatory readiness on ${lowReg.regulation} (current ${lowReg.readiness}%).`);
    const certFocus = certEntries.slice().sort((a, b) => b.score - a.score)[0];
    if (certFocus) out.push(`Maintain momentum on ${formatCertName(certFocus.name)} while backfilling documentation for secondary frameworks.`);
    while (out.length < 4) {
      out.push("Embed KPI reviews into quarterly board reporting to sustain investor-grade disclosure discipline.");
    }
    return out.slice(0, 4);
  }, [gaps, roadmapEntries, regulatory, certEntries]);

  const execInsight = useMemo(() => {
    const stage =
      score >= 75 ? "a strong, execution-ready sustainability posture" : score >= 60 ? "a credible baseline with selective gaps to close" : "foundational signals that warrant accelerated governance focus";
    const cert = certEntries.length ? formatCertName(certEntries[0].name) : "priority certification tracks";
    return `This review positions ${orgName} within ${stage}. Emissions intensity, utility resilience, and ${cert} should anchor the next two quarters of capital and operating decisions. Treat the roadmap as a board-level control document—sequence quick wins to unlock assurance, then scale metering and verification to support external stakeholders.`;
  }, [score, certEntries, orgName]);

  const roadmapOrdered = useMemo(() => {
    const order = ["Immediate", "0–3 Months", "3–6 Months", "6–12 Months", "12+ Months"];
    return [...roadmapEntries].sort(
      (a, b) => order.indexOf(a.timeline) - order.indexOf(b.timeline) || a.action.localeCompare(b.action)
    );
  }, [roadmapEntries]);

  return (
    <div
      id="pdf-report-capture"
      className="fixed left-[-9999px] top-0"
      style={{ width: A4_PORTRAIT_CSS_PX.width, pointerEvents: "none", zIndex: -2, fontFamily: printFont }}
    >
      {/* —— Page 1: Cover + executive snapshot + readiness —— */}
      <PrintPage>
        <div style={{ display: "flex", flexDirection: "column", gap: sectionGap, minHeight: 0 }}>
          <div>
            <p style={{ ...typeMeta, marginBottom: 6 }}>Investor-grade ESG summary</p>
            <h1
              style={{
                margin: 0,
                fontFamily: printFont,
                fontSize: 34,
                fontWeight: 700,
                color: BRAND.ink,
                lineHeight: 1.12,
                letterSpacing: "-0.02em",
              }}
            >
              {orgName}
            </h1>
            <p style={{ margin: "10px 0 0", fontSize: 12, color: BRAND.muted, lineHeight: 1.5, maxWidth: 520 }}>
              Sustainability review — structured for assurance conversations, capital partners, and enterprise ESG programs.
            </p>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1.15fr 0.85fr", gap: sectionGap, alignItems: "stretch" }}>
            <PrintCard style={{ display: "flex", flexDirection: "column", gap: cardPad }}>
              <p style={typeMeta}>Executive snapshot</p>
              <div style={{ display: "flex", gap: grid8 * 3, alignItems: "center" }}>
                <Gauge value={score} />
                <div style={{ flex: 1, display: "grid", gridTemplateColumns: "1fr 1fr", gap: grid8 * 1.5 }}>
                  {[
                    { label: "Readiness stage", value: data.readinessStage },
                    { label: "Overall score", value: `${score} / 100` },
                    { label: "Data confidence", value: `${Math.round(data.confidence * 100)}%` },
                    { label: "Comprehensiveness", value: `${Math.round(data.completeness)}%` },
                  ].map((row) => (
                    <div key={row.label} style={{ borderLeft: `3px solid ${stageColor(score)}`, paddingLeft: grid8 * 1.5 }}>
                      <p style={{ margin: 0, fontSize: 9, fontWeight: 600, color: BRAND.slate, lineHeight: 1.35 }}>{row.label}</p>
                      <p style={{ margin: "4px 0 0", fontSize: 13, fontWeight: 800, color: BRAND.ink, lineHeight: 1.2 }}>{row.value}</p>
                    </div>
                  ))}
                </div>
              </div>
            </PrintCard>
            <PrintCard>
              <p style={typeMeta}>Readiness summary</p>
              <p style={{ margin: "12px 0 0", fontSize: 22, fontWeight: 800, color: stageColor(score) }}>{data.readinessStage}</p>
              <p style={{ margin: "10px 0 0", fontSize: 11, color: BRAND.muted, lineHeight: 1.5 }}>
                Portfolio carbon footprint <strong style={{ color: BRAND.ink }}>{data.totalEmissions.toFixed(1)} tCO₂e</strong> / yr
                (indicative model). Scores reflect uploaded operational evidence and SAM methodology — not a certification outcome.
              </p>
              <div style={{ marginTop: grid8 * 2, paddingTop: grid8 * 2, borderTop: `1px solid ${BRAND.line}` }}>
                <p style={{ margin: 0, fontSize: 9, fontWeight: 600, color: BRAND.slate, lineHeight: 1.35 }}>Sector</p>
                <p style={{ margin: "4px 0 0", fontSize: 13, fontWeight: 700, color: BRAND.ink }}>{data.sector ?? "Healthcare"}</p>
              </div>
            </PrintCard>
          </div>

          <PrintCard style={{ flex: "0 0 auto" }}>
            <p style={typeMeta}>Category performance</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: cardPad, marginTop: cardPad }}>
              {[
                { label: "Energy", value: categoryScores.energy, accent: "#d97706" },
                { label: "Water", value: categoryScores.water, accent: BRAND.blue },
                { label: "Waste", value: categoryScores.waste, accent: BRAND.green },
                { label: "Governance", value: categoryScores.governance, accent: "#6d28d9" },
              ].map((c) => (
                <div key={c.label} style={{ textAlign: "center" }}>
                  <p style={{ margin: 0, fontSize: 10, fontWeight: 700, color: BRAND.slate, lineHeight: 1.3 }}>{c.label}</p>
                  <p style={{ margin: "6px 0 0", fontSize: 22, fontWeight: 900, color: stageColor(c.value), fontFamily: printFont }}>
                    {Math.round(c.value)}
                  </p>
                  <div style={{ marginTop: grid8, height: 5, background: "#e2e8f0", borderRadius: 1, overflow: "hidden" }}>
                    <div style={{ width: `${Math.min(100, Math.max(0, c.value))}%`, height: "100%", background: c.accent }} />
                  </div>
                </div>
              ))}
            </div>
          </PrintCard>

          <p style={{ margin: `${sectionGap}px 0 0`, fontSize: 9, color: BRAND.slate, textAlign: "center", lineHeight: 1.4 }}>
            ESGroww • {generatedLabel}
          </p>
        </div>
      </PrintPage>

      {/* —— Page 2: Categories + emissions + certifications —— */}
      <PrintPage footer={<ReportFooter orgName={orgName} pageLabel="Page 2" generatedLabel={generatedLabel} />}>
        <div style={{ display: "flex", flexDirection: "column", gap: sectionGap, minHeight: 0 }}>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: sectionGap, alignItems: "start" }}>
            <PrintCard style={{ display: "flex", flexDirection: "column" }}>
              <p style={typeMeta}>Emissions profile</p>
              <div style={{ marginTop: cardPad, display: "flex", flexDirection: "column", gap: grid8 * 1.25 }}>
                {[
                  { label: "Scope 1 — direct", value: emissions.scope1, tone: "#b91c1c" },
                  { label: "Scope 2 — indirect energy", value: emissions.scope2, tone: "#c2410c" },
                  { label: "Scope 3 — value chain", value: emissions.scope3, tone: BRAND.yellow },
                ].map((s) => (
                  <div
                    key={s.label}
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      padding: `${grid8 * 1.5}px ${grid8 * 2}px`,
                      background: BRAND.soft,
                      borderRadius: 2,
                      border: `1px solid ${BRAND.line}`,
                    }}
                  >
                    <span style={{ fontSize: 11, fontWeight: 600, color: BRAND.ink, lineHeight: 1.35 }}>{s.label}</span>
                    <span style={{ fontSize: 15, fontWeight: 900, color: s.tone, lineHeight: 1.2 }}>
                      {s.value.toFixed(1)} <span style={{ fontSize: 10, fontWeight: 600, color: BRAND.slate }}>tCO₂e</span>
                    </span>
                  </div>
                ))}
              </div>
            </PrintCard>

            <PrintCard style={{ display: "flex", flexDirection: "column" }}>
              <p style={typeMeta}>Certification readiness</p>
              <div
                style={{
                  marginTop: cardPad,
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: grid8 * 1.25,
                  overflow: "visible",
                }}
              >
                {certEntries.slice(0, 8).map((cert) => {
                  const color = stageColor(cert.score);
                  return (
                    <div
                      key={cert.name}
                      style={{
                        display: "grid",
                        gridTemplateColumns: "auto 1fr auto",
                        alignItems: "center",
                        gap: grid8 * 1.5,
                        padding: `${grid8 * 1.25}px ${grid8 * 1.25}px`,
                        background: BRAND.soft,
                        border: `1px solid ${BRAND.line}`,
                        borderRadius: 2,
                      }}
                    >
                      <div
                        style={{
                          width: 36,
                          height: 36,
                          borderRadius: "50%",
                          border: `2px solid ${color}55`,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: 11,
                          fontWeight: 900,
                          color,
                        }}
                      >
                        {cert.score}
                      </div>
                      <div style={{ minWidth: 0 }}>
                        <p style={{ margin: 0, fontSize: 10, fontWeight: 800, color: BRAND.ink, lineHeight: 1.35, wordBreak: "break-word" }}>
                          {formatCertName(cert.name)}
                        </p>
                        <p style={{ margin: "4px 0 0", fontSize: 9, fontWeight: 600, color: BRAND.slate, lineHeight: 1.35 }}>{cert.status}</p>
                      </div>
                      <div style={{ width: 52, height: 6, background: "#e2e8f0", borderRadius: 99, overflow: "hidden" }}>
                        <div style={{ width: `${cert.score}%`, height: "100%", background: color }} />
                      </div>
                    </div>
                  );
                })}
              </div>
            </PrintCard>
          </div>
        </div>
      </PrintPage>

      {/* —— Page 3: KPI + strengths / gaps + roadmap pathway —— */}
      <PrintPage footer={<ReportFooter orgName={orgName} pageLabel="Page 3" generatedLabel={generatedLabel} />}>
        <div style={{ display: "flex", flexDirection: "column", gap: sectionGap, minHeight: 0 }}>
          <PrintCard style={{ flex: "0 0 auto" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: cardPad, gap: grid8 }}>
              <p style={typeMeta}>KPI scorecards</p>
              <span style={{ fontSize: 9, fontWeight: 700, color: BRAND.blue, lineHeight: 1.3 }}>{kpiRows.length} metrics</span>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: grid8 * 1.25 }}>
              {kpiRows.map((item) => {
                const { bg, fg, label } = kpiImpactStyle(item.kpi);
                const displayVal = item.kpi.value !== null ? item.kpi.value.toFixed(1) : "—";
                return (
                  <div
                    key={item.title}
                    style={{
                      border: `1px solid ${BRAND.line}`,
                      borderRadius: 4,
                      padding: `${grid8 * 1.25}px ${grid8 * 1.25}px`,
                      display: "grid",
                      gridTemplateRows: "auto auto auto auto",
                      gap: 6,
                      background: "#fff",
                    }}
                  >
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 6 }}>
                      <span style={{ fontSize: 10, fontWeight: 800, color: BRAND.ink }}>{item.icon}</span>
                      <span style={{ fontSize: 8, fontWeight: 800, padding: "2px 6px", borderRadius: 2, background: bg, color: fg, lineHeight: 1.25 }}>{label}</span>
                    </div>
                    <p style={{ margin: 0, fontSize: 10, fontWeight: 700, color: BRAND.muted, lineHeight: 1.35 }}>{item.title}</p>
                    <p style={{ margin: 0, fontSize: 18, fontWeight: 900, color: BRAND.ink, fontFamily: printFont, lineHeight: 1.2 }}>
                      {displayVal}
                      <span style={{ fontSize: 9, fontWeight: 600, color: BRAND.slate, marginLeft: 4 }}>{item.unit}</span>
                    </p>
                    <p style={{ margin: 0, fontSize: 9, color: BRAND.slate, lineHeight: 1.35, wordBreak: "break-word" }}>{item.kpi.status}</p>
                  </div>
                );
              })}
            </div>
          </PrintCard>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: sectionGap, alignItems: "start" }}>
            <PrintCard style={{ display: "flex", flexDirection: "column" }}>
              <p style={typeMeta}>Strengths & gaps</p>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  gap: cardPad,
                  marginTop: cardPad,
                  alignItems: "start",
                }}
              >
                <div style={{ display: "flex", flexDirection: "column", gap: grid8 * 1.25, minWidth: 0, width: "100%" }}>
                  <p style={{ margin: 0, fontSize: 9, fontWeight: 800, color: BRAND.green, lineHeight: 1.35 }}>Strengths</p>
                  {strengths.slice(0, 4).map((t, i) => (
                    <div key={i} style={{ padding: grid8 * 1.25, background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 4, fontSize: 10, lineHeight: 1.45, color: "#14532d" }}>
                      {t}
                    </div>
                  ))}
                </div>
                <div style={{ display: "flex", flexDirection: "column", gap: grid8 * 1.25, minWidth: 0, width: "100%" }}>
                  <p style={{ margin: 0, fontSize: 9, fontWeight: 800, color: BRAND.red, lineHeight: 1.35 }}>Gaps</p>
                  {gaps.slice(0, 4).map((g, i) => (
                    <div
                      key={i}
                      style={{
                        padding: grid8 * 1.25,
                        borderRadius: 4,
                        border: `1px solid ${riskColor[g.severity] ?? BRAND.line}55`,
                        background: "#fff",
                        fontSize: 10,
                        lineHeight: 1.45,
                        color: BRAND.ink,
                        display: "flex",
                        flexDirection: "row",
                        alignItems: "flex-start",
                        gap: grid8,
                      }}
                    >
                      <span
                        style={{
                          flex: "0 0 auto",
                          fontSize: 8,
                          fontWeight: 800,
                          color: "#fff",
                          background: riskColor[g.severity] ?? BRAND.slate,
                          padding: "3px 6px",
                          borderRadius: 2,
                          lineHeight: 1.2,
                        }}
                      >
                        {g.severity}
                      </span>
                      <span style={{ flex: 1, minWidth: 0, wordBreak: "break-word" }}>{g.text}</span>
                    </div>
                  ))}
                </div>
              </div>
            </PrintCard>

            <PrintCard style={{ display: "flex", flexDirection: "column" }}>
              <p style={typeMeta}>Executive action pathway</p>
              <div style={{ position: "relative", marginTop: cardPad }}>
                <div
                  style={{
                    position: "absolute",
                    left: 18,
                    top: 10,
                    bottom: 10,
                    width: 2,
                    background: `linear-gradient(180deg, ${BRAND.line}, #cbd5e1)`,
                    borderRadius: 1,
                  }}
                />
                <div style={{ display: "flex", flexDirection: "column", gap: grid8 * 1.25, paddingLeft: grid8 * 5 }}>
                  {roadmapOrdered.slice(0, 5).map((item, index) => {
                    const color = roadmapColor[item.timeline] ?? BRAND.slate;
                    return (
                      <div key={index} style={{ display: "flex", gap: grid8 * 1.25, alignItems: "flex-start" }}>
                        <div
                          style={{
                            width: 14,
                            height: 14,
                            marginTop: 3,
                            marginLeft: -32,
                            borderRadius: "50%",
                            background: "#fff",
                            border: `3px solid ${color}`,
                            flexShrink: 0,
                          }}
                        />
                        <div style={{ flex: 1, minWidth: 0, border: `1px solid ${BRAND.line}`, borderRadius: 4, padding: grid8 * 1.25, background: "#fff" }}>
                          <div style={{ display: "flex", justifyContent: "space-between", gap: grid8, marginBottom: 4, alignItems: "flex-start" }}>
                            <p style={{ margin: 0, fontSize: 10, fontWeight: 800, color: BRAND.ink, lineHeight: 1.35 }}>{item.action}</p>
                            <span style={{ fontSize: 8, fontWeight: 800, color, whiteSpace: "nowrap", lineHeight: 1.3, flexShrink: 0 }}>{item.timeline}</span>
                          </div>
                          <p style={{ margin: 0, fontSize: 9, color: BRAND.muted, lineHeight: 1.45 }}>{item.impact}</p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </PrintCard>
          </div>
        </div>
      </PrintPage>

      {/* —— Page 4: Regulatory + executive insight + recommendations —— */}
      <PrintPage footer={<ReportFooter orgName={orgName} pageLabel="Page 4" generatedLabel={generatedLabel} />}>
        <div style={{ display: "flex", flexDirection: "column", gap: sectionGap, minHeight: 0 }}>
          <PrintCard style={{ display: "flex", flexDirection: "column", flex: "0 0 auto" }}>
            <p style={typeMeta}>Regulatory readiness</p>
            <div style={{ marginTop: cardPad, display: "flex", flexDirection: "column", gap: grid8 * 1.25 }}>
              {regulatory.slice(0, 7).map((reg, i) => (
                <div key={i} style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                  <div style={{ display: "grid", gridTemplateColumns: "1fr 52px 52px", gap: grid8 * 1.5, alignItems: "start" }}>
                    <p
                      style={{
                        margin: 0,
                        paddingTop: 2,
                        fontSize: 10,
                        fontWeight: 700,
                        color: BRAND.ink,
                        lineHeight: 1.4,
                        wordBreak: "break-word",
                        overflowWrap: "anywhere",
                        minWidth: 0,
                      }}
                    >
                      {reg.regulation}
                    </p>
                    <span style={{ fontSize: 11, fontWeight: 900, textAlign: "right", lineHeight: 1.3, paddingTop: 2 }}>{reg.readiness}%</span>
                    <span
                      style={{
                        fontSize: 8,
                        fontWeight: 800,
                        textAlign: "center",
                        padding: "4px 4px",
                        borderRadius: 4,
                        lineHeight: 1.25,
                        background: `${riskColor[reg.risk] ?? BRAND.slate}22`,
                        color: BRAND.ink,
                        border: `1px solid ${riskColor[reg.risk] ?? BRAND.slate}44`,
                      }}
                    >
                      {reg.risk}
                    </span>
                  </div>
                  <div style={{ height: 5, background: "#e2e8f0", borderRadius: 1, overflow: "hidden" }}>
                    <div style={{ width: `${reg.readiness}%`, height: "100%", background: riskColor[reg.risk] ?? BRAND.blue }} />
                  </div>
                </div>
              ))}
            </div>
          </PrintCard>

          <div
            style={{
              borderRadius: 4,
              padding: cardPad * 1.33,
              border: "1px solid #86efac",
              background: "linear-gradient(135deg, #ecfdf5 0%, #f8fafc 70%, #ffffff 100%)",
              position: "relative",
              overflow: "hidden",
            }}
          >
            <p style={{ ...typeMeta, color: "#166534" }}>Executive insight</p>
            <p
              style={{
                margin: "10px 0 0",
                fontSize: 12,
                lineHeight: 1.55,
                color: BRAND.ink,
                fontFamily: printFont,
                fontWeight: 500,
              }}
            >
              “{execInsight}”
            </p>
          </div>

          <PrintCard style={{ display: "flex", flexDirection: "column" }}>
            <p style={typeMeta}>Final recommendations</p>
            <ol style={{ margin: `${cardPad}px 0 0`, paddingLeft: 18, color: BRAND.ink, fontSize: 11, lineHeight: 1.5 }}>
              {recommendations.map((r, i) => (
                <li key={i} style={{ marginBottom: 6 }}>
                  {r}
                </li>
              ))}
            </ol>
          </PrintCard>
        </div>
      </PrintPage>
    </div>
  );
}
