/*
  Warnings:

  - You are about to drop the column `waterKl` on the `WaterData` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "ElectricityData" ADD COLUMN     "electricityCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "meterReading" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "peakDemand" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "powerFactor" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "FuelData" ADD COLUMN     "dgRuntimeHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dieselCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pngCngQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "TransportData" ADD COLUMN     "cargoTonnage" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "fleetFuelConsumption" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tonneKilometers" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vehicleKilometers" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "WasteData" ADD COLUMN     "authorizedVendorDisposalKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "constructionWasteKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "dryWasteKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eWasteKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "hazardousWasteKg" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "wetWasteKg" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "WaterData" DROP COLUMN "waterKl",
ADD COLUMN     "borewellWaterKl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "municipalWaterKl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "rainwaterHarvestedKl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tankerWaterKl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalWaterConsumptionKl" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "waterCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
